[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'w0ng/vim-hybrid'
hook_add = '''
set background=dark
colorscheme hybrid
'''

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = 'fzf'

[[plugins]]
repo = 'junegunn/fzf'
build = './install --all'
merged = 0

[[plugins]]
repo = '~/ngswitcher.vim'
hook_add = '''
nnoremap <leader>u :<C-u>NgSwitchTS<CR>
nnoremap <leader>i :<C-u>NgSwitchCSS<CR>
nnoremap <leader>o :<C-u>NgSwitchHTML<CR>
nnoremap <leader>p :<C-u>NgSwitchSpec<CR>

nnoremap <leader>su :<C-u>SNgSwitchTS<CR>
nnoremap <leader>si :<C-u>SNgSwitchCSS<CR>
nnoremap <leader>so :<C-u>SNgSwitchHTML<CR>
nnoremap <leader>sp :<C-u>SNgSwitchSpec<CR>

nnoremap <leader>vu :<C-u>VNgSwitchTS<CR>
nnoremap <leader>vi :<C-u>VNgSwitchCSS<CR>
nnoremap <leader>vo :<C-u>VNgSwitchHTML<CR>
nnoremap <leader>vp :<C-u>VNgSwitchSpec<CR>

nnoremap <leader>l :<C-u>NgShowList<CR>
'''
